benchmark_lm_head_only: False
model_id: meta-llama/Llama-3.2-3B-Instruct
device: cpu

prompt: "Who was Alan Turing?"
batch_size: 1
new_token_count: 1

is_ref: false
ef: 200
k: 50

autorange_min_run_time: 10.0
